<a href="https://colab.research.google.com/github/Amy-codes-stuff/collage-is-making-me-code-this-/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Single layer

In [1]:
import numpy as np

inputs = [0.5, 0.2, 0.8]
weights = [0.1, 0.3, -0.2]
bias = 0.1

output = np.dot(inputs, weights) + bias
print(output)

0.049999999999999975


Multilayer

In [2]:
inputs = [0.5, 0.2, 0.8, 0.1]
weights = [[0.1, 0.2, -0.1],
           [-0.3, 0.4, 0.2],
           [0.5, -0.5, 0.6],
           [-0.2, 0.1, -0.4]]
bias  = [0.1,0.2,0.3]

output = np.dot(inputs, weights) + bias
print(output)

[ 0.47 -0.01  0.73]


Data batch

In [4]:
input_databatch =[
    [0.5, 0.2, 0.8, 0.1],           #1st row is first set of inputs x1,x2,x3,x4
    [0.1, 0.3, -0.2, 0.9],
    [0.9, 0.7, 0.6, 0.4],
    [0.3, 0.8, 0.1, 0.5],
    [0.6, 0.9, 0.3, 0.7],
    [0.2, 0.4, 0.7, 0.2]
]

weight = [
    [0.1, 0.2, -0.1],
    [-0.3, 0.4, 0.2],
    [0.5, -0.5, 0.6],
    [-0.2, 0.1, -0.4]]

bias = [0.1, 0.2, 0.3]

output = np.dot(input_databatch, np.array(weight)) + bias
print(output)



[[ 0.47 -0.01  0.73]
 [-0.26  0.53 -0.13]
 [ 0.2   0.4   0.55]
 [-0.16  0.58  0.29]
 [-0.1   0.6   0.32]
 [ 0.31  0.07  0.7 ]]
